In [8]:
r = 100
t = 0.2

total = r * (1 + t)
total

120.0

In [9]:
100 > 50
100 == 50
100 != 50

True

In [10]:
print ((100 > 50) and (20 < 30))

True

In [11]:
sales = [100, 200, 150, 200]
sales

[100, 200, 150, 200]

In [12]:
sales[0]
sales[-1]

200

In [13]:
sales.append(300)
sales[1] = 250
sales

[100, 250, 150, 200, 300]

In [14]:
sales.remove(150)
sales

[100, 250, 200, 300]

In [15]:
len(sales)

4

In [16]:
len(sales)

4

In [17]:
total = 0
for value in sales:
    total += value

total

850

In [18]:
coordinates = (40.18, 44.51)
coordinates

(40.18, 44.51)

In [20]:
customer_ids = {1, 2, 3, 3, 4}
customer_ids

{1, 2, 3, 4}

In [22]:
s1 = {1, 2, 3}

In [24]:
s2 = set([1,2,2,3])

In [25]:
empty_set = set()

In [27]:
s1.add(4)

In [28]:
s = {1, 2, 3}

In [29]:
s.add(4)

In [36]:
s.remove(2)

KeyError: 2

In [37]:
s.remove(1)

In [38]:
s.add(1)

In [39]:
s.discard(5)

In [40]:
s.pop()

1

In [41]:
s.pop()

3

In [42]:
print(s)

{4}

In [43]:
3 in s

False

In [44]:
4 in s

True

In [45]:
s.add(1, 2, 3, 5, 6)

TypeError: set.add() takes exactly one argument (5 given)

In [46]:
s.add(1)

In [47]:
print(s)

{1, 4}

In [48]:
segment_a = {1, 2, 3}
segment_b = {3, 4, 5}

In [49]:
segment_a & segment_b

{3}

In [50]:
segment_a | segment_b

{1, 2, 3, 4, 5}

In [51]:
segment_a - segment_b

{1, 2}

In [52]:
segment_b - segment_a

{4, 5}

In [53]:
segment_a ^ segment_b

{1, 2, 4, 5}

In [55]:
transactions = [101, 102, 102, 103, 104]

In [56]:
unique_transactions = set(transactions)
unique_transactions

{101, 102, 103, 104}

In [58]:
campaign_a = {1, 2, 3, 4}
campaign_b = {3, 4, 5, 6}

In [59]:
overlap = campaign_a & campaign_b
overlap

{3, 4}

In [60]:
new_customers = campaign_b - campaign_a
new_customers

{5, 6}

In [61]:
valid_ids = {1, 2, 3, 4, 5}
incoming_ids = {2, 3, 6}

In [63]:
invalid_ids = incoming_ids - valid_ids

In [64]:
print(invalid_ids)

{6}

In [65]:
# This will fail
s = {[1, 2], [3, 4]}

TypeError: unhashable type: 'list'

In [70]:
customer = {
    "name": "Anna",
    "revenue": 150,
    "city": "Yerevan"
}

In [71]:
customer

{'name': 'Anna', 'revenue': 150, 'city': 'Yerevan'}

In [72]:
customer["revenue"]

150

In [73]:
customer["segment"] = "Premium"
customer["revenue"] = 200
customer

{'name': 'Anna', 'revenue': 200, 'city': 'Yerevan', 'segment': 'Premium'}

In [74]:
del customer["city"]
customer

{'name': 'Anna', 'revenue': 200, 'segment': 'Premium'}

In [75]:
customers = [
    {"name": "Anna", "revenue": 150},
    {"name": "David", "revenue": 220},
    {"name": "Mariam", "revenue": 90}
]

customers

[{'name': 'Anna', 'revenue': 150},
 {'name': 'David', 'revenue': 220},
 {'name': 'Mariam', 'revenue': 90}]

In [76]:
import pandas as pd

In [77]:
data = {
    "name": ["Anna" "David" "Mariam"],
    "revenue": [150, 220, 90],
    "city": ["Yerevan", "Tbilisi", "Warsaw"] 
}

In [81]:


df = pd.DataFrame(data)
df

     name  revenue     city
0    Anna      150  Yerevan
1   David      220  Tbilisi
2  Mariam       90   Warsaw

In [82]:
df.info()
df.shape
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     3 non-null      str
 1   revenue  3 non-null      int64
 2   city     3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

Index(['name', 'revenue', 'city'], dtype='str')

In [83]:
df["revenue"]
df[["name", "revenue"]]

     name  revenue
0    Anna      150
1   David      220
2  Mariam       90

In [84]:
t = 0.2
df["revenue_after_tax"] = df["revenue"] * (1 - t)
df

     name  revenue     city  revenue_after_tax
0    Anna      150  Yerevan              120.0
1   David      220  Tbilisi              176.0
2  Mariam       90   Warsaw               72.0

In [85]:
df.drop("city", axis=1)

     name  revenue  revenue_after_tax
0    Anna      150              120.0
1   David      220              176.0
2  Mariam       90               72.0

In [86]:
df = df.drop("city", axis=1)
df

     name  revenue  revenue_after_tax
0    Anna      150              120.0
1   David      220              176.0
2  Mariam       90               72.0

In [87]:
df[df["revenue"] > 100]

    name  revenue  revenue_after_tax
0   Anna      150              120.0
1  David      220              176.0

In [90]:
df.loc[df["revenue"] < 100, "segment"] = "Low"
df.loc[df["revenue"] >= 100, "segment"] = "High"
df

     name  revenue  revenue_after_tax segment
0    Anna      150              120.0    High
1   David      220              176.0    High
2  Mariam       90               72.0     Low

In [91]:
revenue = 150

if revenue > 100:
    print("High revenue")
else:
    print("Normal revenue")

High revenue

In [92]:
revenue = 150

if revenue > 100:
    print("High revenue")
    
print("Analysis complete")

High revenue
Analysis complete

In [93]:
revenue = 150

if revenue > 100:
print("High revenue")   # IndentationError

IndentationError: expected an indented block after 'if' statement on line 3 (2779987221.py, line 4)

In [94]:
revenue = 180

In [96]:
if revenue > 200:
    print("Very high revenue")
elif revenue > 100:
    print("High revenue")
elif revenue > 50:
    print("Medium revenue")
else:
    print("Low revenue")

High revenue

In [97]:
revenue = 150
is_active = True

In [99]:
if revenue > 100 and is_active:
    print("Target customer")

Target customer

In [100]:
is_active = False

In [101]:
if not is_active:
    print("Customer is inactive")

Customer is inactive

In [102]:
revenue = 150
region = "EU"

In [105]:
if revenue > 100:
    if region == "EU":
        print("High EU revenue")
    else:
        print("High non-Eu revenue")

High EU revenue

In [106]:
if revenue = 100:   # SyntaxError

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (3933434082.py, line 1)

In [108]:
if revenue == 100:
    print("Equal")

In [109]:
print("Equal")

Equal

In [110]:
if revenue > 100
    print("High")

SyntaxError: expected ':' (1163908359.py, line 1)

In [112]:
if revenue > 100:
print("High")

IndentationError: expected an indented block after 'if' statement on line 1 (4030861262.py, line 2)

In [113]:
if revenue > 100:
    print("High")

High

In [114]:
sales = [100, 200, 150]

In [116]:
for value in sales:
    print(value)

100
200
150

In [117]:
sales = [100, 200, 150]

total = 0

for value in sales:
    total = total + value

total

450

In [118]:
sales = [100, 200, 150, 50]

In [119]:
for value in sales:
    if value > 120:
        print("High sale:", value)

High sale: 200
High sale: 150

In [120]:
customer = {
    "name": "Anna",
    "revenue": 150,
    "city": "Yerevan"
}

In [121]:
for key in customer:
    print(key, ":", customer[key])

name : Anna
revenue : 150
city : Yerevan

In [122]:
for key, value in customer.items():
    print(key, value)

name Anna
revenue 150
city Yerevan

In [125]:
for i in range(5):
    print(i)

0
1
2
3
4

In [126]:
for i in range(3):
    for j in range(2):
        print("i =", i, ", j =", j)

i = 0 , j = 0
i = 0 , j = 1
i = 1 , j = 0
i = 1 , j = 1
i = 2 , j = 0
i = 2 , j = 1

In [129]:
sales = [100, 200, 150]

new_sales = []

for value in sales:
    new_sales.append(value * 1.2)

new_sales

[120.0, 240.0, 180.0]

In [130]:
sales = [100, 200, 150]

new_sales = [value * 1.2 for value in sales]
new_sales

[120.0, 240.0, 180.0]

In [131]:
sales = [100, 200, 150, 50]

high_sales = [value for value in sales if value > 120]
high_sales

[200, 150]

In [132]:
high_sales = []

for value in sales:
    if value > 120:
        high_sales.append(value)

high_sales

[200, 150]