In [ ]:
import pandas as pd

In [5]:
df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head(10)

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0
6,550135,1,prior,7,1,9,20.0
7,3108588,1,prior,8,1,14,14.0
8,2295261,1,prior,9,1,16,0.0
9,2550362,1,prior,10,4,8,30.0

In [6]:
# Reading data
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [7]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [10]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['department'], dtype='str')
(21, 1)

  department
0     frozen
1      other
2     bakery
3    produce
4    alcohol

In [11]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.head())

  department
0     frozen
1      other
2     bakery
3    produce
4    alcohol

In [19]:
df_departments = df_departments.reset_index()
print(df_departments.shape)

(21, 2)

In [21]:
df_departments = df_departments.reset_index()

In [22]:
print(df_departments.columns)

Index(['index', 'department'], dtype='str')

In [25]:
if df_departments.shape[1] == 1:
    df_departments = df_departments.reset_index()

print(df_departments.columns)
print(df_departments.shape)

Index(['index', 'department'], dtype='str')
(21, 2)

In [26]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['department'], dtype='str')
(21, 1)

  department
0     frozen
1      other
2     bakery
3    produce
4    alcohol

In [28]:
if df_departments.shape[1] == 1:
    df_departments = df_departments.reset_index()

In [29]:
df_departments.rename(columns={'index': 'department_id'}, inplace=True)

In [30]:
print(df_departments.columns)
print(df_departments.shape)

Index(['department_id', 'department'], dtype='str')
(21, 2)

In [32]:
df_departments = df_departments.reset_index()

In [33]:
df_departments.rename(columns={'index': 'department_id'}, inplace=True)

In [34]:
df_departments.to_csv('../data/processed/departments_t.csv', index=False)

In [35]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['department_id', 'department'], dtype='str')
(21, 2)

   department_id department
0              0     frozen
1              1      other
2              2     bakery
3              3    produce
4              4    alcohol

In [36]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [37]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [38]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [39]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [40]:
pd.options.display.float_format = '{:,.2f}'.format
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [41]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [42]:
df_orders["order_id"].nunique()

3421083

In [43]:
df_orders["user_id"].nunique()

206209

In [44]:
df_orders["eval_set"].value_counts(dropna=False)

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [45]:
df_orders["order_dow"].value_counts().sort_index()

order_dow
0    600905
1    587478
2    467260
3    436972
4    426339
5    453368
6    448761
Name: count, dtype: int64

In [46]:
df_orders["order_hour_of_day"].value_counts().sort_index()

order_hour_of_day
0      22758
1      12398
2       7539
3       5474
4       5527
5       9569
6      30529
7      91868
8     178201
9     257812
10    288418
11    284728
12    272841
13    277999
14    283042
15    283639
16    272553
17    228795
18    182912
19    140569
20    104292
21     78109
22     61468
23     40043
Name: count, dtype: int64

In [47]:
df_orders["days_since_prior_order"].isna().sum()

np.int64(206209)

In [48]:
df_orders.loc[df_orders["order_number"] == 1, "days_since_prior_order"].isna().all()

np.True_

In [49]:
df_orders["order_id"].is_unique

True

In [50]:
df_orders["order_dow"].between(0, 6).all()

np.True_

In [51]:
df_orders["order_hour_of_day"].between(0, 23).all()

np.True_

In [52]:
df_orders_train = df_orders[df_orders["eval_set"] == "train"]
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [53]:
df_orders_train.drop(columns=["eval_set"])
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [54]:
del df_orders

In [55]:
df_orders_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [56]:
df_orders_products_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 1384617 entries, 0 to 1384616
Data columns (total 4 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   order_id           1384617 non-null  int64
 1   product_id         1384617 non-null  int64
 2   add_to_cart_order  1384617 non-null  int64
 3   reordered          1384617 non-null  int64
dtypes: int64(4)
memory usage: 42.3 MB

In [57]:
df_orders_products_train.dtypes

order_id             int64
product_id           int64
add_to_cart_order    int64
reordered            int64
dtype: object

In [58]:
df_orders_products_train.describe()

          order_id   product_id  add_to_cart_order    reordered
count 1,384,617.00 1,384,617.00       1,384,617.00 1,384,617.00
mean  1,706,297.62    25,556.24               8.76         0.60
std     989,732.65    14,121.27               7.42         0.49
min           1.00         1.00               1.00         0.00
25%     843,370.00    13,380.00               3.00         0.00
50%   1,701,880.00    25,298.00               7.00         1.00
75%   2,568,023.00    37,940.00              12.00         1.00
max   3,421,070.00    49,688.00              80.00         1.00

In [59]:
df_orders_products_train.isna().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [60]:
len(df_orders_products_train)

1384617

In [61]:
df_orders_products_train["order_id"].nunique()

131209

In [62]:
df_orders_products_train["product_id"].nunique()

39123

In [63]:
df_orders_products_train["reordered"].value_counts(dropna=False)

reordered
1    828824
0    555793
Name: count, dtype: int64

In [64]:
df_orders_products_train["reordered"].value_counts(normalize=True)

reordered
1   0.60
0   0.40
Name: proportion, dtype: float64

In [65]:
df_orders_products_train["add_to_cart_order"].describe()

count   1,384,617.00
mean            8.76
std             7.42
min             1.00
25%             3.00
50%             7.00
75%            12.00
max            80.00
Name: add_to_cart_order, dtype: float64

In [66]:
df_orders_products_train["add_to_cart_order"].value_counts().sort_index().head(20)

add_to_cart_order
1     131209
2     124364
3     116996
4     108963
5     100745
6      91850
7      83142
8      74601
9      66618
10     59401
11     52848
12     46814
13     41431
14     36588
15     32194
16     28363
17     24841
18     21733
19     19014
20     16541
Name: count, dtype: int64

In [67]:
df_orders_products_train["order_id"].is_unique

False

In [68]:
df_orders_products_train["product_id"].is_unique

False

In [69]:
df_orders_products_train["reordered"].isin([0, 1]).all()

np.True_

In [70]:
(df_orders_products_train["add_to_cart_order"] > 0).all()

np.True_

In [71]:
df_orders_products_train[["order_id", "product_id"]].isna().sum()

order_id      0
product_id    0
dtype: int64

In [72]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [73]:
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 49693 entries, 0 to 49692
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49693 non-null  int64
 1   product_name   49677 non-null  str
 2   aisle_id       49693 non-null  int64
 3   department_id  49693 non-null  int64
 4   prices         49693 non-null  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.9 MB

In [74]:
df_products.dtypes

product_id         int64
product_name         str
aisle_id           int64
department_id      int64
prices           float64
dtype: object

In [75]:
df_products.describe()

       product_id  aisle_id  department_id    prices
count   49,693.00 49,693.00      49,693.00 49,693.00
mean    24,844.35     67.77          11.73      9.99
std     14,343.72     38.32           5.85    453.52
min          1.00      1.00           1.00      1.00
25%     12,423.00     35.00           7.00      4.10
50%     24,845.00     69.00          13.00      7.10
75%     37,265.00    100.00          17.00     11.20
max     49,688.00    134.00          21.00 99,999.00

In [76]:
df_products.isna().sum()

product_id        0
product_name     16
aisle_id          0
department_id     0
prices            0
dtype: int64

In [77]:
df_products["product_id"].nunique()

49686

In [78]:
df_products["product_id"].is_unique

False

In [79]:
df_products["department_id"].nunique()

21

In [80]:
df_products["aisle_id"].nunique()

134

In [81]:
df_products["product_name"].duplicated().sum()

np.int64(20)

In [82]:
df_products[["product_id", "product_name", "aisle_id", "department_id"]].head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [83]:
df_products["product_id"].is_unique

False

In [84]:
df_products["department_id"].isna().sum()

np.int64(0)

In [85]:
df_products["aisle_id"].isna().sum()

np.int64(0)

In [86]:
df_departments.head()

   department_id department
0              0     frozen
1              1      other
2              2     bakery
3              3    produce
4              4    alcohol

In [87]:
df_departments.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     str
dtypes: int64(1), str(1)
memory usage: 468.0 bytes

In [88]:
df_departments.dtypes

department_id    int64
department         str
dtype: object

In [89]:
df_departments.isna().sum()

department_id    0
department       0
dtype: int64

In [90]:
df_departments["department"].nunique()

21

In [91]:
df_departments["department_id"].is_unique

True

In [92]:
df_departments.isna().sum()

department_id    0
department       0
dtype: int64

In [93]:
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [94]:
df_aisles.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   aisle_id  134 non-null    int64
 1   aisle     134 non-null    str
dtypes: int64(1), str(1)
memory usage: 2.2 KB

In [95]:
df_aisles.dtypes

aisle_id    int64
aisle         str
dtype: object

In [96]:
df_aisles["aisle"].nunique()

134

In [98]:
df_aisles["aisle_id"].is_unique

True

In [99]:
df_aisles.isna().sum()

aisle_id    0
aisle       0
dtype: int64

In [103]:
df_merged = pd.merge(df_products, df_departments, on="department_id", how="left")

In [104]:
df_merged.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,deli
1,2,All-Seasons Salt,104,13,9.30,breakfast
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,pets
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,other
4,5,Green Chile Anytime Sauce,5,13,4.30,breakfast

In [105]:
pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="inner"
).head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,deli
1,2,All-Seasons Salt,104,13,9.30,breakfast
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,pets
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,other
4,5,Green Chile Anytime Sauce,5,13,4.30,breakfast

In [106]:
pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left"
).head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,deli
1,2,All-Seasons Salt,104,13,9.30,breakfast
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,pets
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,other
4,5,Green Chile Anytime Sauce,5,13,4.30,breakfast

In [107]:
pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="outer",
    indicator=True
).head()

,product_id,product_name,aisle_id,department_id,prices,department,_merge
0,NaN,NaN,NaN,0,NaN,frozen,right_only
1,4.00,Smart Ones Classic Favorites Mini Rigatoni Wit...,38.00,1,10.50,other,both
2,8.00,Cut Russet Potatoes Steam N' Mash,116.00,1,1.10,other,both
3,12.00,Chocolate Fudge Layer Cake,119.00,1,9.40,other,both
4,18.00,Pizza for One Suprema Frozen Pizza,79.00,1,10.60,other,both

In [115]:
df_departments = df_departments[df_departments['department_id'] != 0]

In [116]:
df_merged = pd.merge(df_products, df_departments, on="department_id", how="outer")
df_merged.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,other
1,8,Cut Russet Potatoes Steam N' Mash,116,1,1.10,other
2,12,Chocolate Fudge Layer Cake,119,1,9.40,other
3,18,Pizza for One Suprema Frozen Pizza,79,1,10.60,other
4,30,"Three Cheese Ziti, Marinara with Meatballs",38,1,13.80,other

In [117]:
df_products_departments = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left"
)

df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,deli
1,2,All-Seasons Salt,104,13,9.30,breakfast
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,pets
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,other
4,5,Green Chile Anytime Sauce,5,13,4.30,breakfast

In [118]:
df_products_departments_check = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left",
    indicator=True
)

df_products_departments_check.head()

,product_id,product_name,aisle_id,department_id,prices,department,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.80,deli,both
1,2,All-Seasons Salt,104,13,9.30,breakfast,both
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,pets,both
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,other,both
4,5,Green Chile Anytime Sauce,5,13,4.30,breakfast,both

In [119]:
df_products_departments_check["_merge"].value_counts()

_merge
both          48435
left_only      1258
right_only        0
Name: count, dtype: int64

In [120]:
df_products_departments_check[
    df_products_departments_check["_merge"] == "left_only"
].head()

,product_id,product_name,aisle_id,department_id,prices,department,_merge
37,38,Ultra Antibacterial Dish Liquid,100,21,13.40,NaN,left_only
71,72,Organic Honeycrisp Apples,100,21,10.70,NaN,left_only
109,110,Uncured Turkey Bologna,100,21,7.60,NaN,left_only
296,297,"Write Bros Ball Point Pens, Cap-Pen, Medium (1...",100,21,8.80,NaN,left_only
416,417,Classics Baby Binks Easter Chocolate Bunny,100,21,2.80,NaN,left_only

In [121]:
df_products_departments = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left"
)

df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,deli
1,2,All-Seasons Salt,104,13,9.30,breakfast
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,pets
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,other
4,5,Green Chile Anytime Sauce,5,13,4.30,breakfast